# Generated by Django 5.0 on 2024-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=30)),
                ('category', models.IntegerField()),
                ('pdeatils', models.CharField(max_length=50)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
